### PR TITLE
Support contributions with no type and allow 'flogo install' for any …

### PR DESCRIPTION
**Pull request by pointlander**
…go package

### CODE REVIEW

**Comment by fm-tibco** [comment]
This only effects packages that have a descriptor.json that doesn't have a "type".  Is that what this is for?  From a quick look at the code it looks like it will work if you have a go pkg that doesn't have a descriptor.json.

**Comment by pointlander** [comment]
'flogo install' fails when there isn't a descriptor.json and the package that is being installed is not a action/trigger/activity.

**Comment by pointlander** [comment]
This looks like the root cause of the problem:
https://github.com/project-flogo/cli/blob/master/util/flogo.go#L78
If there are other JSON files in the package, a file that isn't a descriptor could be opened and used.

**Comment by fm-tibco** [comment]
I’ll merge this in and create a separate PR that will look specifically for our descriptor files.

**Pull request merged**
